# This is a plugin developed by RiesPanda
# You can contact me here
# Discord - RiesPanda#3952
# Spigot - https://www.spigotmc.org/members/riespanda.710163/


# This will change the amount lost when dying (Percentage).
lost-balance: 25

# This will change the message when a player dies.
# (Keep in mind, the amount will always appear after the message).
death-message: "&6You have died and lost "

# This will change the permission's name
perm-name: ""